"""use array for numbers, remove DrawNumbers

Revision ID: 05949cce3c79
Revises: 15c64ca0727c
Create Date: 2026-04-21 14:36:02.712353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05949cce3c79'
down_revision: Union[str, Sequence[str], None] = '15c64ca0727c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('game_code', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('game_code')
    )
    op.create_table('bingoextra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('lot_special', sa.Integer(), nullable=False),
    sa.Column('lot_big_small', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lot_odd_even', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['draw_id'], ['drawslist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('drawnumbers')
    op.add_column('drawslist', sa.Column('numbers', postgresql.ARRAY(sa.INTEGER()), nullable=True))
    op.alter_column('drawslist', 'game_code',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='game_code::integer')
    op.alter_column('drawslist', 'next_draw_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.create_foreign_key(None, 'drawslist', 'game', ['game_code'], ['game_code'])
    op.drop_column('drawslist', 'game_name')
    op.drop_column('drawslist', 'special_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawslist', sa.Column('special_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drawslist', sa.Column('game_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'drawslist', type_='foreignkey')
    op.alter_column('drawslist', 'next_draw_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('drawslist', 'game_code',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('drawslist', 'numbers')
    op.create_table('drawnumbers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('draw_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['draw_id'], ['drawslist.id'], name=op.f('drawnumbers_draw_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drawnumbers_pkey'))
    )
    op.drop_table('bingoextra')
    op.drop_table('game')
    # ### end Alembic commands ###
