"""add source verification and discrepancy table

Revision ID: 15c64ca0727c
Revises: 36ec0bd0febc
Create Date: 2026-04-20 17:36:40.806348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '15c64ca0727c'
down_revision: Union[str, Sequence[str], None] = '36ec0bd0febc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawdiscrepancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('api_numbers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('official_numbers', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_special', sa.Integer(), nullable=True),
    sa.Column('official_special', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draw_id'], ['drawslist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drawslist', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('drawslist', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('drawslist', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('drawslist', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawslist', 'updated_at')
    op.drop_column('drawslist', 'verified_at')
    op.drop_column('drawslist', 'is_verified')
    op.drop_column('drawslist', 'source')
    op.drop_table('drawdiscrepancy')
    # ### end Alembic commands ###
