"""init

Revision ID: 36ec0bd0febc
Revises: 
Create Date: 2026-04-16 14:45:08.494107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '36ec0bd0febc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawslist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('next_draw_date', sa.Date(), nullable=False),
    sa.Column('special_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawnumbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draw_id'], ['drawslist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drawnumbers')
    op.drop_table('drawslist')
    # ### end Alembic commands ###
