"""change draw_date to datetime

Revision ID: 40ab085c9382
Revises: 05949cce3c79
Create Date: 2026-04-21 17:13:11.068541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '40ab085c9382'
down_revision: Union[str, Sequence[str], None] = '05949cce3c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drawslist', 'draw_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drawslist', 'draw_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
