"""add slug to game

Revision ID: bbd2ae93eee0
Revises: 47fec680c2b2
Create Date: 2026-04-24 11:08:39.394656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'bbd2ae93eee0'
down_revision: Union[str, Sequence[str], None] = '47fec680c2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('game', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    op.execute("UPDATE game SET slug = 'big-lotto' WHERE game_code = 5118")
    op.execute("UPDATE game SET slug = 'power-lotto' WHERE game_code = 5134")
    op.execute("UPDATE game SET slug = '539' WHERE game_code = 5120")
    op.execute("UPDATE game SET slug = 'bingo' WHERE game_code = 1102")
    op.execute("UPDATE game SET slug = '39lotto' WHERE game_code = 1197")
    op.execute("UPDATE game SET slug = '49lotto' WHERE game_code = 1121")
    op.execute("UPDATE game SET slug = '3star' WHERE game_code = 2108")
    op.execute("UPDATE game SET slug = '4star' WHERE game_code = 2109")

    op.alter_column('game', 'slug', nullable=False)
    op.create_unique_constraint('uq_game_slug', 'game', ['slug'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_game_slug', 'game', type_='unique')
    op.drop_column('game', 'slug')
    # ### end Alembic commands ###
